export const QUERY_KEYS = {
  cryptoList: "cryptoList",
  exchangeRates: "exchangeRates",
  allPerpMetas: "allPerpMetas",
  spotMeta: "spotMeta",
  perpDexs: "perpDexs",
  tradeTicker: "tradeTicker",
  extraAgents: "userExtraAgents",
  maxBuilderFee: "maxBuilderFee",
  portfolio: "portfolio",
  delegatorSummary: "delegatorSummary",
  userFees: "user-fees",
  predictionMarketEvents: "predictionMarketEvents",
  settledOutcome: "settledOutcome",
} as const;
