import { KlineIndicator } from "../types";

// TODO: Save the indicators in indexedDB for local persistence and customization
export const INDICATORS: Record<string, KlineIndicator> = {
  MA: {
    name: "MA",
    showSeries: true,
    params: [
      {
        period: 7,
        lineWidth: 1,
        color: "#F0B90B",
        source: "close",
        visible: true,
      },
      {
        period: 25,
        lineWidth: 1,
        color: "#EB40B5",
        source: "close",
        visible: true,
      },
      {
        period: 99,
        lineWidth: 1,
        color: "#B385F8",
        source: "close",
        visible: true,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#D63864",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#50AE55",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#F37F20",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#AF6CC3",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#5FC3D7",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#2961FF",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#43DB5D",
        source: "close",
        visible: false,
      },
    ],
    // periods: [7, 25, 99, 0, 0, 0, 0, 0, 0, 0],
    // lineWidths: ["1", "1", "1", "1", "1", "1", "1", "1", "1", "1"],
    // visibles: [
    //   true,
    //   true,
    //   true,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    // ],
    // colors: [
    //   { type: "color", value: "#F0B90B" },
    //   { type: "color", value: "#EB40B5" },
    //   { type: "color", value: "#B385F8" },
    //   { type: "color", value: "#D63864" },
    //   { type: "color", value: "#50AE55" },
    //   { type: "color", value: "#F37F20" },
    //   { type: "color", value: "#AF6CC3" },
    //   { type: "color", value: "#5FC3D7" },
    //   { type: "color", value: "#2961FF" },
    //   { type: "color", value: "#43DB5D" },
    // ],
  },
  EMA: {
    name: "EMA",
    showSeries: true,
    params: [
      {
        period: 6,
        lineWidth: 1,
        color: "#F0B90B",
        source: "close",
        visible: true,
      },
      {
        period: 12,
        lineWidth: 1,
        color: "#EB40B5",
        source: "close",
        visible: true,
      },
      {
        period: 20,
        lineWidth: 1,
        color: "#B385F8",
        source: "close",
        visible: true,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#D63864",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#50AE55",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#F37F20",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#AF6CC3",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#5FC3D7",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#2961FF",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#43DB5D",
        source: "close",
        visible: false,
      },
    ],
    // periods: [6, 12, 20, 0, 0, 0, 0, 0, 0, 0],
    // lineWidths: ["1", "1", "1", "1", "1", "1", "1", "1", "1", "1"],
    // visibles: [
    //   true,
    //   true,
    //   true,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    // ],
    // colors: [
    //   { type: "color", value: "#F0B90B" },
    //   { type: "color", value: "#EB40B5" },
    //   { type: "color", value: "#B385F8" },
    //   { type: "color", value: "#D63864" },
    //   { type: "color", value: "#50AE55" },
    //   { type: "color", value: "#F37F20" },
    //   { type: "color", value: "#AF6CC3" },
    //   { type: "color", value: "#5FC3D7" },
    //   { type: "color", value: "#2961FF" },
    //   { type: "color", value: "#43DB5D" },
    // ],
  },

  WMA: {
    name: "WMA",
    showSeries: true,
    params: [
      {
        period: 5,
        lineWidth: 1,
        color: "#F0B90B",
        source: "close",
        visible: true,
      },
      {
        period: 10,
        lineWidth: 1,
        color: "#EB40B5",
        source: "close",
        visible: true,
      },
      {
        period: 30,
        lineWidth: 1,
        color: "#B385F8",
        source: "close",
        visible: true,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#D63864",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#50AE55",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#F37F20",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#AF6CC3",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#5FC3D7",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#2961FF",
        source: "close",
        visible: false,
      },
      {
        period: 0,
        lineWidth: 1,
        color: "#43DB5D",
        source: "close",
        visible: false,
      },
    ],
    // periods: [5, 10, 30, 0, 0, 0, 0, 0, 0, 0],
    // lineWidths: ["1", "1", "1", "1", "1", "1", "1", "1", "1", "1"],
    // visibles: [
    //   true,
    //   true,
    //   true,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    //   false,
    // ],
    // colors: [
    //   [
    //     { type: "color", value: "#F0B90B" },
    //     { type: "color", value: "#EB40B5" },
    //     { type: "color", value: "#B385F8" },
    //     { type: "color", value: "#D63864" },
    //     { type: "color", value: "#50AE55" },
    //     { type: "color", value: "#F37F20" },
    //     { type: "color", value: "#AF6CC3" },
    //     { type: "color", value: "#5FC3D7" },
    //     { type: "color", value: "#2961FF" },
    //     { type: "color", value: "#43DB5D" },
    //   ],
    // ],
  },
};
// More indicators to be added later
// { BBI: { name: "BBI", periods: [3, 6, 12, 24] } },
// { VOL: { name: "VOL", periods: [5, 10, 20] } },
// { MACD: { name: "MACD", periods: [12, 26, 9] } },
// { BOLL: { name: "BOLL", periods: [20] } },
// { KDJ: { name: "KDJ", periods: [9, 3, 3] } },
// { RSI: { name: "RSI", periods: [6, 12, 24] } },
// { BIAS: { name: "BIAS", periods: [6, 12, 24] } },
// { BRAR: { name: "BRAR", periods: [26] } },
// { CCI: { name: "CCI", periods: [13] } },
// { DMI: { name: "DMI", periods: [14, 6] } },
// { CR: { name: "CR", periods: [26, 10, 20, 40, 60] } },
// { PSY: { name: "PSY", periods: [12, 6] } },
// { DMA: { name: "DMA", periods: [10, 50, 10] } },
// { TRIX: { name: "TRIX", periods: [12, 20] } },
// { OBV: { name: "OBV", periods: [30] } },
// { VR: { name: "VR", periods: [24, 30] } },
// { WR: { name: "WR", periods: [6, 10, 14] } },
// { MTM: { name: "MTM", periods: [6, 10] } },
// { EMV: { name: "EMV", periods: [14, 9] } },
// { SAR: { name: "SAR", periods: [2, 2, 20] } },
// { AO: { name: "AO", periods: [5, 34] } },
// { ROC: { name: "ROC", periods: [12, 6] } },
// { PVT: { name: "PVT", periods: null } },
// { AVP: { name: "AVP", periods: null } },
