// Note: We can consider using AI to generate categories for each market event

export const PREDICTION_CATEGORIES = {
  sports: ["football", "soccer", "basketball", "tennis", "cricket", "olympics"],
  crypto: [
    "bitcoin",
    "btc",
    "ethereum",
    "eth",
    "solana",
    "sol",
    "hyperliquid",
    "hype",
    "hypurr",
    "blockchain",
    "crypto",
    "nft",
    "defi",
    "coin",
    "memecoin",
  ],
  politics: ["election", "government", "president", "senate", "parliament"],
  tech: [
    "ai",
    "software",
    "hardware",
    "tesla",
    "apple",
    "google",
    "launch",
    "technology",
    "robotics",
    "gpt",
  ],
  finance: [
    "stock",
    "bond",
    "etf",
    "s&p",
    "sp500",
    "interest rate",
    "inflation",
    "fed",
    "market",
    "perpetual",
    "margin",
  ],
  economy: [
    "gdp",
    "cpi",
    "unemployment",
    "recession",
    "economic growth",
    "economy",
  ],
  science: ["physics", "biology", "astronomy", "research", "chemistry"],
  //   art: ["painting", "sculpture", "gallery", "exhibition", "modern art"],
  entertainment: [
    "movie",
    "oscar",
    "grammy",
    "tv show",
    "music",
    "celebrity",
    "hollywood",
    "netflix",
  ],
  business: ["company", "startup", "merger", "corporation", "entrepreneur"],
  other: [],
} as const;
